# runs unit testing with jest

name: Unit testing

on:
  pull_request:
  workflow_dispatch:
  
jobs: 
  run-unit-tests:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install all dependencies
        run: npm install
        
      - name: Run Test
        run: npm run unit-test
